Student_Name =input("Enter Your Name: ")
Student_Age=int(input("Enter your Age: "))
Course_Name=input("Enter your Course Name: ")
Course_duration=input("Enter your Course Duration: ")
Course_Fee=float(input("Enter your Course Fee: "))
Enrollment_Status=bool(input("Enter your enrollment Status: "))
print("___________________Student Data__________________________")
print()
print("Student Name: ",Student_Name)
print("Student Age: ",Student_Age)
print("Course Name: ",Course_Name)
print("Course Duration",Course_duration)
print("Course Fee: ",Course_Fee)
print("Enrollment Status: ",Enrollment_Status)